In [1]:
import torch

快捷键：shift + tab 可以查看方法的说明文档

In [4]:
# 使用 arange 创建一个行向量 x
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
# 可以通过张量的shape属性来访问张量（沿每个轴的长度）的形状 
x.shape

torch.Size([12])

In [11]:
# 元素数量
x.numel()

12

In [23]:
# 改变一个张量的形状而不改变元素数量和元素值，可以调用reshape函数
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [20]:
X.shape

torch.Size([3, 4])

In [24]:
X.numel()

12

In [26]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [27]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [30]:
torch.randn(3, 4) # 标准正态分布 （均值0方差1）

tensor([[-0.9606,  0.4624, -0.3594, -0.8974],
        [ 0.1080,  0.6339,  0.7755,  1.5464],
        [ 0.3467,  0.5626, -0.6163,  0.0185]])

In [6]:
torch.rand(3, 4) # 区间[0,1)的均匀分布

tensor([[0.4570, 0.2467, 0.1292, 0.1740],
        [0.6330, 0.9220, 0.9257, 0.5346],
        [0.7113, 0.7848, 0.8763, 0.1063]])

In [31]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [32]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [8]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X,Y),dim=0), torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [40]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [13]:
X.sum()

tensor(66.)

## 广播机制

In [43]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [44]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 截取tensor的一部分：产生一个新的tensor对象

In [21]:
X[-1],X[1:3], X[:2, :2]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[0., 1.],
         [4., 5.]]))

In [20]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [51]:
X[1,2] = 9 # 修改tensor某一处值
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [53]:
before = id(Y)
Y = Y + X
id(Y) == before  # 计算会产生新的tensor

False

 使用切片表示法将操作的结果分配给先前分配的数组

In [56]:
Z = torch.zeros_like(Y)
print(id(Z))
Z[:] = X + Y # 修改整个tensor的值，没有产生新的tensor
print(id(Z))

1742148881536
1742148881536


In [58]:
before = id(X)
X += Y
id(X) == before

True

In [60]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

### 练习题

In [62]:
X,Y

(tensor([[ 4.,  7., 18., 21.],
         [22., 29., 51., 43.],
         [48., 51., 54., 57.]]),
 tensor([[ 2.,  3.,  8.,  9.],
         [ 9., 12., 21., 18.],
         [20., 21., 22., 23.]]))

In [64]:
X > Y ,X < Y

(tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [86]:
x1 = torch.randn(2,3,1)
x2 = torch.randn(1,1,2)
x1,x2

(tensor([[[ 0.6960],
          [-1.4785],
          [-0.4621]],
 
         [[-2.5840],
          [-1.0108],
          [ 1.1953]]]),
 tensor([[[-0.0678, -0.7388]]]))

In [87]:
x1 + x2

tensor([[[ 0.6281, -0.0428],
         [-1.5463, -2.2173],
         [-0.5300, -1.2009]],

        [[-2.6519, -3.3228],
         [-1.0787, -1.7496],
         [ 1.1275,  0.4565]]])